# Generated by Django 4.1 on 2024-11-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0002_nomina_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_beneficios',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='total_deducciones',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
