# Generated by Django 4.1 on 2024-11-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0004_nomina_nombre_empresa_alter_nomina_salario_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20),
            preserve_default=False,
        ),
    ]
