# Generated by Django 4.1 on 2024-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0002_jornada_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='cantidad_horas',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
