# Generated by Django 4.2.16 on 2024-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(max_length=16)),
                ('numero_inss', models.CharField(max_length=11)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='F', max_length=1)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
