# Generated by Django 4.2.16 on 2024-10-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
