# Generated by Django 4.1 on 2024-11-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargos_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='descripcion',
            field=models.CharField(default='mediante diversos medios', max_length=255),
            preserve_default=False,
        ),
    ]
