# Generated by Django 4.1 on 2024-10-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_beneficios_nombre_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
