# Generated by Django 4.1 on 2024-10-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_beneficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_beneficios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
