# Generated by Django 4.1 on 2024-11-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_personales', '0002_documentos_personales_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos_personales',
            name='direccion_archivo',
        ),
    ]
