# Generated by Django 4.1 on 2024-11-06 17:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_personales', '0003_remove_documentos_personales_direccion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos_personales',
            name='archivo',
            field=models.FileField(default='C:\\Admin_RH_Documentos\\documentos_personales\\Captura de pantalla 2024-11-06 103207.png', storage=django.core.files.storage.FileSystemStorage(location='C:/Admin_RH_Documentos/'), upload_to='documentos_personales/'),
            preserve_default=False,
        ),
    ]
