# Generated by Django 4.1 on 2024-11-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0004_nomina_nombre_empresa_alter_nomina_salario_bruto_and_more'),
        ('contratos', '0002_contrato_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_nomina',
            field=models.ForeignKey(db_column='id_nomina', default=1, on_delete=django.db.models.deletion.CASCADE, to='nominas.nomina'),
            preserve_default=False,
        ),
    ]
