# Generated by Django 4.1 on 2024-11-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_id_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='id_nomina',
        ),
    ]
