# Generated by Django 4.2.16 on 2024-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deducciones',
            name='nombre_deduccion',
            field=models.CharField(default='PRUEBA', max_length=20),
            preserve_default=False,
        ),
    ]
