# Generated by Django 4.1 on 2024-10-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
