# Generated by Django 4.1 on 2024-11-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_permiso_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='id_empleados',
        ),
    ]
