# Generated by Django 4.2.16 on 2024-10-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Contratos',
            fields=[
                ('id_historial_contratos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('codigo_contrato_anterior', models.CharField(max_length=8)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
            ],
        ),
    ]
