# Generated by Django 4.2.16 on 2024-10-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('salarios', '0001_initial'),
        ('tipo_deducciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Deducciones',
            fields=[
                ('id_detalle_deduciones', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salarios.salario')),
                ('id_tipo_deducciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_deducciones.tipo_deducciones')),
            ],
        ),
    ]
