# Generated by Django 4.1 on 2024-11-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_nomina', '0002_detalle_nomina_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_nomina',
            name='id_salario',
        ),
    ]
