# Generated by Django 4.1 on 2024-11-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_nomina', '0003_remove_detalle_nomina_id_salario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_nomina',
            name='descripcion',
        ),
    ]
