# Generated by Django 4.1 on 2024-11-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_remove_contrato_id_nomina'),
        ('detalle_nomina', '0004_remove_detalle_nomina_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_nomina',
            name='id_contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_nomina',
            name='monto_beneficios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalle_nomina',
            name='monto_deducciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalle_nomina',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalle_nomina',
            name='salario_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
