# Generated by Django 4.2.16 on 2024-10-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_beneficios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_beneficios',
            name='id_tipo_beneficios',
        ),
    ]
