# Generated by Django 4.1 on 2024-10-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_beneficios', '0003_detalle_beneficios_id_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_beneficios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
