# Generated by Django 4.1 on 2024-11-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_beneficios', '0004_detalle_beneficios_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_beneficios',
            name='id_salario',
        ),
    ]
