# Generated by Django 4.1 on 2024-11-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_is_active'),
        ('detalle_beneficios', '0005_remove_detalle_beneficios_id_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_beneficios',
            name='id_contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
            preserve_default=False,
        ),
    ]
